overriding_tools:
  - void_additions:pointy_stick
  - void_additions:pointy_stone
default_blocks:
  - CAVE_VINES_PLANT
  - SWEET_BERRY_BUSH
  - SNOW
  - SHORT_GRASS
  - TALL_GRASS
  - SHORT_DRY_GRASS
  - TALL_DRY_GRASS
  - SEAGRASS
  - TALL_SEAGRASS
  - PALE_HANGING_MOSS
  - FERN
  - TALL_FERN
  - BUSH
  - DEAD_BUSH
  - LEAF_LITTER
  - VINES
  - HANGING_ROOTS
  - GLOW_LICHEN
  - FIREFLY_BUSH
  - MOSS_CARPET
  - PALE_MOSS_CARPET
  - CACTUS_FLOWER
  - OAK_SAPLING
  - SPRUCE_SAPLING
  - BIRCH_SAPLING
  - JUNGLE_SAPLING
  - ACACIA_SAPLING
  - DARK_OAK_SAPLING
  - CHERRY_SAPLING
  - PALE_OAK_SAPLING
  - MANGROVE_PROPAGULE
  - AZALEA
  - FLOWERING_AZALEA
  - OAK_LEAVES
  - SPRUCE_LEAVES
  - BIRCH_LEAVES
  - JUNGLE_LEAVES
  - ACACIA_LEAVES
  - DARK_OAK_LEAVES
  - CHERRY_LEAVES
  - PALE_OAK_LEAVES
  - MANGROVE_LEAVES
  - AZALEA_LEAVES
  - FLOWERING_AZALEA_LEAVES
  - MUSHROOM_STEM
  - BROWN_MUSHROOM_BLOCK
  - RED_MUSHROOM_BLOCK
