default_whitelisted_blocks:
  - GRAVEL
  - OAK_LEAVES
  - SPRUCE_LEAVES
  - BIRCH_LEAVES
  - JUNGLE_LEAVES
  - CHERRY_LEAVES
  - MANGROVE_LEAVES
  - DARK_OAK_LEAVES
  - ACACIA_LEAVES
  - GRASS
  - TALL_GRASS
whitelisted_tools:
  - void_additions:pointy_stick
  - void_additions:pointy_stone