# The maximum durability of the item.
max_durability: 4
# The damage the item takes when it is used to attack an entity.
item_damage_on_attack_entity: 2
# The damage the item takes when it is used to break a block.
item_damage_on_break_block: 1
# The repair ingredient that can be used in anvils.
repair_ingredient: "minecraft:stick"
#burn time
burn_time: 0.25
# wowzers
whitelisted_blocks:
  STONE:
    replace_with: COBBLESTONE
    drop_item: "void_additions:stone_pebble"
    chance: 100
    break_speed: 8
  COBBLESTONE:
    replace_with: GRAVEL
    drop_item: "void_additions:stone_pebble"
    chance: 100
    break_speed: 6
  GRAVEL:
    replace_with: NOTHING
    break_speed: 6
  OAK_LOG:
    replace_with: STRIPPED_OAK_LOG
    drop_item: "minecraft:stick"
    chance: 100
    break_speed: 6
  STRIPPED_OAK_LOG:
    replace_with: STRIPPED_OAK_LOG
    drop_item: "minecraft:stick"
    chance: 100
    break_speed: 5