# The maximum durability of the item.
max_durability: 12
# The damage the item takes when it is used to attack an entity.
item_damage_on_attack_entity: 2
# The damage the item takes when it is used to break a block.
item_damage_on_break_block: 1
# The repair ingredient that can be used in anvils.
repair_ingredient: "voidadditions:stone_pebble"
# Which blocks should player be able to break
whitelisted_blocks:
  STONE:
    replace_with: COBBLESTONE
    drop_item: "void_additions:stone_pebble"
    chance: 100
    break_speed: 6
  COBBLESTONE:
    replace_with: GRAVEL
    drop_item: "void_additions:stone_pebble"
    chance: 100
    break_speed: 5
  GRAVEL:
    replace_with: NOTHING
    break_speed: 4
  OAK_LOG:
    replace_with: STRIPPED_OAK_LOG
    drop_item: "minecraft:stick"
    chance: 100
    break_speed: 4
  STRIPPED_OAK_LOG:
    replace_with: STRIPPED_OAK_LOG
    drop_item: "minecraft:stick"
    chance: 100
    break_speed: 3